version: '3'
services: 

  mysql:
    image: 'mysql'
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express-sequelize
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks: 
      - 'database-net'
    volumes: 
      - ./data:/var/lib/mysql
  
  adminer:
    image: 'adminer'
    ports:
      - '4000:8080'
    networks: 
      - 'database-net'

networks:
  database-net: